version: '3.8'

services:
  train:
    build: .
    command: python train_model.py
    volumes:
      - .:/app
    restart: "no"

  predict:
    build: .
    command: python predict.py
    volumes:
      - .:/app
    restart: "no"

  drift_monitor:
    build: .
    command: python drift_monitor.py
    volumes:
      - .:/app
    restart: "no"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - train
      - predict
      - drift_monitor
